# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_app_development
  username: your_db_username
  password: your_db_password

test:
  <<: *default
  database: your_app_test
  username: your_db_username
  password: your_db_password

production:
  <<: *default
  database: your_app_production
  url: <%= ENV['DATABASE_URL'] %>
