default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_app_development
  username: your_db_username
  # password: your_db_password  # Leave this line out if not needed

test:
  <<: *default
  database: your_app_test
  username: your_db_username
  # password: your_db_password  # Leave this line out if not needed

production:
  <<: *default
  database: your_app_production
  username: your_db_username
  password: <%= ENV['YOUR_DB_PASSWORD'] %>  # Ensure this environment variable is set in production
  host: your_db_host